// Lu Yixuan, Deborah, A0277911X
// Test cases generated by ChatGPT. Reviewed and edited by me afterwards

import orderModel from "./orderModel.js";

describe("orderModel", () => {
  const oid1 = "507f1f77bcf86cd799439011";
  const oid2 = "507f1f77bcf86cd799439012";
  const oid3 = "507f1f77bcf86cd799439013";

  describe("Happy Path Tests - when everything works as expected, the model", () => {
    test("should be registered with model name Order", () => {
      const modelName = orderModel.modelName;
      expect(modelName).toBe("Order");
    });

    test("should define products, payment, buyer, status fields in schema", () => {
      const schemaPaths = orderModel.schema.paths;

      expect(schemaPaths.products).toBeDefined();
      expect(schemaPaths.payment).toBeDefined();
      expect(schemaPaths.buyer).toBeDefined();
      expect(schemaPaths.status).toBeDefined();
    });

    test("should default status to 'Not Process' when not provided", () => {
      const order = new orderModel({
        products: [],
        buyer: oid1,
        payment: {},
      });

      expect(order.status).toBe("Not Process");
    });

    test("should allow validation with valid enum status values", () => {
      const validStatuses = ["Not Process", "Processing", "Shipped", "delivered", "cancel"];

      for (const s of validStatuses) {
        const order = new orderModel({
          products: [],
          buyer: oid1,
          payment: {},
          status: s,
        });

        const err = order.validateSync();

        expect(err).toBeUndefined();
        expect(order.status).toBe(s);
      }
    });

    test("should allow validation with minimal fields (since none are required)", () => {
      const order = new orderModel({});
      const err = order.validateSync();

      expect(err).toBeUndefined();
    });

    test("should cast buyer and products to ObjectId from valid hex strings", () => {
      const order = new orderModel({
        buyer: oid1,
        products: [oid2, oid3],
        payment: {},
      });

      const err = order.validateSync();

      expect(err).toBeUndefined();
      expect(String(order.buyer)).toBe(oid1);
      expect(order.products).toHaveLength(2);
      expect(String(order.products[0])).toBe(oid2);
      expect(String(order.products[1])).toBe(oid3);
    });
  });

  describe("Unhappy Path Tests - when there are issues, the model", () => {
    test("should reject invalid status values not in enum", () => {
      const order = new orderModel({
        products: [],
        buyer: oid1,
        payment: {},
        status: "INVALID_STATUS",
      });

      const err = order.validateSync();

      expect(err).toBeDefined();
      expect(err.errors.status).toBeDefined();
    });

    test("should error when buyer is not castable to ObjectId", () => {
      const order = new orderModel({
        products: [],
        buyer: "not-an-objectid",
        payment: {},
      });

      const err = order.validateSync();

      expect(err).toBeDefined();
      expect(err.errors.buyer).toBeDefined();
    });

    test("should error when products contains a value not castable to ObjectId", () => {
      const order = new orderModel({
        products: ["not-an-objectid"],
        buyer: oid1,
        payment: {},
      });

      const err = order.validateSync();

      expect(err).toBeDefined();
      expect(err.errors["products.0"]).toBeDefined();
    });
  });
});